on:
  push:
    branches:
      - master

name: Deploy Demo
jobs:
  deploy:
    name: Build & Deploy Demo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js 10.17
        uses: actions/setup-node@v1
        with:
          node-version: 10.17
      - name: Cache node_modules
        id: cache-modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('package.json') }}
      - name: Install Dependencies
        if: steps.cache-modules.outputs.cache-hit != 'true'
        run: npm install
      - name: Build
        run: |
          npm run build
      - name: Make 404.html
        run: cp index.html 404.html
        working-directory: __sapper__/export/frank-the-collie
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: __sapper__/export/frank-the-collie
