on:
  schedule:
    # At 12:00 on the 1st every month
    - cron:  '0 12 1 * *'

name: Refresh Instagram Photos
jobs:
  deploy:
    name: Build & Deploy Demo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: pip install instagram-scraper
      - name: Scrape images
        env:
          INSTAGRAM_PASS: ${{secrets.INSTAGRAM_PASS}}
          INSTAGRAM_USER: frankthecollie
          INSTAGRAM_TARGET: frankthecollie
        run: instagram-scraper $INSTAGRAM_TARGET -u $INSTAGRAM_USER -p $INSTAGRAM_PASS -t image --maximum 20 --destination ./static/insta-feed --latest-stamps ./static/insta-feed.cache.txt --media_metadata -T {shortcode}
      - name: Save to Repo
        uses: EndBug/add-and-commit@v7
        with:
          add: "./static/insta-feed/*.jpg ./static/insta-feed/*.json ./static/insta-feed.cache.txt"
          message: "Scraped instagram photos"
          default_author: github_actions
